---
title: Is Prime (normal)
description: Test if a given number is a prime number
instructions: |
    <p>
        In this exercise you must implement a function <var>is_prime</var>
        that returns true if a given number is a prime.
    </p>

view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: primes.py

#feedback_template: access/task_direct.html

template_files:
  - isprime/primes.py

container:
  image: apluslms/grade-python
  mount: isprime_base/container
  cmd: run-all-unittests
